### PR TITLE
Configure algorithm runtime, don't schedule data object nodes as algortihms

### PR DESCRIPTION
**Pull request by ottjk**
BEGINRELEASENOTES
- Algorithms now handled as a callable struct containing graph information
- Data objects no longer scheduled as tasks

Struct allows algorithm to access information about its vertex, including average runtime and size.
Ideas taken from @m-fila in #19.

ENDRELEASENOTES

### CODE REVIEW

**Comment by m-fila** [comment]
A future of an algorithm execution is stored in the successor DataObject vertices. I like this conceptually but would it work also for graphs in which all the paths are terminated by a algorithm (consumer algorithm that only takes input but doesn't produce any output)?
I'd expect it can be a problem since we'd "lose"  the future and don't have anything to wait for (or attach a notify graph finalization task to)

**Comment by m-fila** [comment]
I tried with `data/sequential/df.graphml` (terminating with consumer algorithm instead of data object) from master and got an error

How about the `schedule_graph` return a vector of tasks for all the terminating algorithms?
By terminating I mean algorithms that don't have a successor algorithm -> so either have no direct successors at all (no data object produced) or their direct successor have no successors (data objects produces but not used anywhere else).
This vector can be later given to `notify_graph_finalization` if scheduling multiple graphs or just awaited directly if scheduling a single graph

`schedule_graph` could check each algorithm vertex with something like

```julia
function is_terminating_alg(graph::AbstractGraph, vertex_id::Int)
    successor_dataobjects = outneighbors(graph, vertex_id)
    is_terminating(vertex) = isempty(outneighbors(graph, vertex))
    all(is_terminating, successor_dataobjects)
end
```

and then append `Dagger.@spawn`ed task if needed

What do you think?

**Comment by ottjk** [comment]
We could store futures in the algorithm as well as its children, which should resolve it. I do like the idea of `schedule_graph` returning a list of all the terminating algorithms though - that way we don't have to iterate through the whole graph again afterwards. Maybe we do both?

**Comment by m-fila** [comment]
> We could store futures in the algorithm as well as its children, which should resolve it. I do like the idea of `schedule_graph` returning a list of all the terminating algorithms though - that way we don't have to iterate through the whole graph again afterwards. Maybe we do both?

Both is good

**Pull request merged**
